In [15]:
from PIL import Image
import os

ori_path = r'dataset_license/train/images'
#token_list = os.listdir(ori_path)
data_path = r'dataset_license/train/images_train'

In [16]:
if not os.path.exists(data_path):
    os.mkdir(data_path)
    

In [17]:
data_list = os.listdir(ori_path)
print(len(data_list))

2053


In [18]:
print(data_list[0])

2004---_-------_--------_jpeg_jpg.rf.d3778565982b14aa4992b73db81f79fd.jpg


In [30]:
import cv2
import numpy as np

for name in data_list:
    im = cv2.imread(ori_path + '/' + rf'{name}')
    height, width, channel = im.shape
    gray = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
    image_blur = cv2.GaussianBlur(gray, ksize=(5,5), sigmaX=0)#이미지를 잘 인식시키기위해 가우시안 블러 사용

    kernel = np.array([[0,-1,0],
                   [-1,5,-1],
                   [0,-1,0]]) #커널 생성
    image_sharp = cv2.filter2D(image_blur,-1,kernel) # 블러 처리 된 이미지를 선명화 시키는 작업
#선명화된 이미지를 이진화 처리(영역마다 빛 조건이 달라질 때 도움이 됨) -> 번호판은 빛 조건이 달라 질 수 있어서 이진화를 함
#cv2.adaptiveThreshold(입력 이미지, 최댓값, 적응형 이진화 플래그, 임곗값 형식, 블록 크기, 감산값)
    max_output_value = 255 #출력 픽셀 강도의 최대값을 결정
    neighborhood_size = 51 #블록의 크기(홀수만 가능)
    substract_from_mean = 10 #감산값
    image_binarized = cv2.adaptiveThreshold(image_sharp, max_output_value,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                                        cv2.THRESH_BINARY,neighborhood_size,substract_from_mean)
    contours, _ = cv2.findContours(
    image_binarized,
    mode=cv2.RETR_LIST,
    method=cv2.CHAIN_APPROX_SIMPLE
    )

    temp_result = np.zeros((height, width, channel), dtype=np.uint8)

    cv2.drawContours(temp_result, contours=contours, contourIdx=-1, color=(255,255,255))
    cv2.imwrite(data_path + '/' + name,temp_result)
    

In [31]:
train_list = os.listdir(data_path)
print(len(train_list))

2053


In [32]:
ori_test_path = r'dataset_license/test/images'
data_test_path = r'dataset_license/test/images_test'

if not os.path.exists(data_test_path):
    os.mkdir(data_test_path)

data_test_list = os.listdir(ori_test_path)
print(len(data_test_list))

475


In [33]:
import cv2
import numpy as np

for name in data_test_list:
    im = cv2.imread(ori_test_path + '/' + rf'{name}')
    height, width, channel = im.shape
    gray = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
    image_blur = cv2.GaussianBlur(gray, ksize=(5,5), sigmaX=0)#이미지를 잘 인식시키기위해 가우시안 블러 사용

    kernel = np.array([[0,-1,0],
                   [-1,5,-1],
                   [0,-1,0]]) #커널 생성
    image_sharp = cv2.filter2D(image_blur,-1,kernel) # 블러 처리 된 이미지를 선명화 시키는 작업
#선명화된 이미지를 이진화 처리(영역마다 빛 조건이 달라질 때 도움이 됨) -> 번호판은 빛 조건이 달라 질 수 있어서 이진화를 함
#cv2.adaptiveThreshold(입력 이미지, 최댓값, 적응형 이진화 플래그, 임곗값 형식, 블록 크기, 감산값)
    max_output_value = 255 #출력 픽셀 강도의 최대값을 결정
    neighborhood_size = 51 #블록의 크기(홀수만 가능)
    substract_from_mean = 10 #감산값
    image_binarized = cv2.adaptiveThreshold(image_sharp, max_output_value,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                                        cv2.THRESH_BINARY,neighborhood_size,substract_from_mean)
    contours, _ = cv2.findContours(
    image_binarized,
    mode=cv2.RETR_LIST,
    method=cv2.CHAIN_APPROX_SIMPLE
    )

    temp_result = np.zeros((height, width, channel), dtype=np.uint8)

    cv2.drawContours(temp_result, contours=contours, contourIdx=-1, color=(255,255,255))
    cv2.imwrite(data_test_path + '/' + name,temp_result)

In [34]:
test_list = os.listdir(data_test_path)
print(len(test_list))

475


In [29]:
for name in data_list[:10]:
    im = cv2.imread(ori_path + '/' + rf'{name}')
    print(im)

[[[207 153 106]
  [204 152 105]
  [200 150 104]
  ...
  [108  64  27]
  [119  75  38]
  [128  84  47]]

 [[212 160 113]
  [205 156 108]
  [199 150 104]
  ...
  [120  76  39]
  [130  86  49]
  [138  94  57]]

 [[221 175 127]
  [210 164 116]
  [197 154 105]
  ...
  [132  90  53]
  [140  98  61]
  [147 105  68]]

 ...

 [[ 76  50  36]
  [ 76  50  36]
  [ 76  50  36]
  ...
  [ 78  53  37]
  [ 79  54  38]
  [ 79  54  38]]

 [[ 70  44  30]
  [ 70  44  30]
  [ 70  44  30]
  ...
  [ 68  43  27]
  [ 69  44  28]
  [ 69  44  28]]

 [[ 69  43  29]
  [ 69  43  29]
  [ 68  42  28]
  ...
  [ 69  44  28]
  [ 69  44  28]
  [ 69  44  28]]]
[[[168 162 157]
  [168 162 157]
  [168 162 157]
  ...
  [167 155 149]
  [168 156 150]
  [168 156 150]]

 [[168 162 157]
  [168 162 157]
  [169 163 158]
  ...
  [163 151 145]
  [164 152 146]
  [164 152 146]]

 [[169 163 158]
  [169 163 158]
  [169 163 158]
  ...
  [168 156 150]
  [169 157 151]
  [169 157 151]]

 ...

 [[ 32  32  32]
  [ 32  32  32]
  [ 32  32  32]
  ..